### ISSUE TITLE
Clicking Login T1 causes exception

### ISSUE THREAD

**Issue by dgxhubbard** [damienbod/ApiJwtWithTwoSts#17]
I ran the project got the home page then clicked "Login T1". 
Got this exception:
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://localhost:44318/.well-known/openid-configuration'

Not really sure what caused this. I am new to openiddict.

**Comment by damienbod** [comment]
Hi @dgxhubbard 

The T1 STS project is not started. You need to start all UI projects. In visual studio, you can setup multiple projects start

Greetings Damien

**Comment by dgxhubbard** [comment]
Thanks Damien. Appreciate it.
